In [1]:
from farPoint import SDRCurves
import pickle


aa = SDRCurves(100.0, 201, 0.5, 0.1, 0.01, 2, 4, useFile='ks1_SDRrec.pick')
aa.getSDRLength()

1053.22461457
460.320774706
xs1 to reach L: 460.320774706
flowrate: 0.00260874607476
flowate at t1: 0.00108746323366
z = 0.41685284903
running two step
running return curve
1.0 0.000854987973338
2.0 0.00271441761659
3.0 0.00533533995674
4.0 0.00861773876013
5.0 0.0125
6.0 0.0169386485199
7.0 0.0219006366099
8.0 0.0273596151468
9.0 0.0332938630035
10.0 0.0396850262992
11.0 0.0465172980696
12.0 0.0537768569587
13.0 0.0614514676489
14.0 0.0695301871865
15.0 0.0780031433644
16.0 0.086861363731
17.0 0.0960966411429
18.0 0.105701426312
19.0 0.115668740695
20.0 0.125992104989
21.0 0.13666547978
22.0 0.147683215781
23.0 0.159040011752
24.0 0.170730878616
25.0 0.182751108638
26.0 0.195096248782
27.0 0.207762077521
28.0 0.220744584567
29.0 0.23403995303
30.0 0.247644543667
31.0 0.261554880894
32.0 0.275767640324
33.0 0.29027963762
34.0 0.305087818482
35.0 0.320189249627
36.0 0.335581110643
37.0 0.351260686596
38.0 0.367225361317
39.0 0.383472611278
40.0 0.4
41.0 0.416805172931
42.0 0.43388585274

ana_new.py:210: RuntimeWarning: invalid value encountered in double_scalars
  + alpha/ie1*ih**m)
ana_new.py:212: RuntimeWarning: invalid value encountered in double_scalars
  - alpha/ie1*m*(ih + ie1*t)**m-1)


47.0 0.523347036173
48.0 0.542036752635
49.0 0.560987872197
50.0 0.580198604202
51.0 0.599667206073
52.0 0.619391981102
53.0 0.639371276375
54.0 0.659603480833
55.0 0.680087023447
56.0 0.700820371516
57.0 0.721802029055
58.0 0.743030535286
59.0 0.764504463209
60.0 0.786222418263
61.0 0.808183037053
62.0 0.830384986156
63.0 0.852826960981
64.0 0.875507684698
65.0 0.898425907223
66.0 0.921580404246
67.0 0.944969976324
68.0 0.968593448001
69.0 0.992449666988
70.0 1.01653750337
71.0 1.04085584887
72.0 1.06540361611
73.0 1.09017973795
74.0 1.11518316684
75.0 1.14041287417
76.0 1.16586784973
77.0 1.19154710109
78.0 1.21744965309
79.0 1.24357454731
80.0 1.26992084157
81.0 1.29648760949
82.0 1.32327393995
83.0 1.35027893676
84.0 1.37750171815
85.0 1.40494141642
86.0 1.43259717753
87.0 1.46046816074
88.0 1.48855353823
89.0 1.51685249478
90.0 1.54536422745
91.0 1.5740879452
92.0 1.60302286865
93.0 1.63216822976
94.0 1.66152327153
95.0 1.69108724774
96.0 1.72085942268
97.0 1.75083907089
98.0 1.78

464.0 23.7769771291
465.0 23.8624442779
466.0 23.9480340481
467.0 24.033746352
468.0 24.1195811021
469.0 24.2055382111
470.0 24.291617592
471.0 24.3778191581
472.0 24.4641428227
473.0 24.5505884996
474.0 24.6371561027
475.0 24.7238455463
476.0 24.8106567447
477.0 24.8975896127
478.0 24.9846440652
479.0 25.0718200173
480.0 25.1591173844
481.0 25.2465360822
482.0 25.3340760264
483.0 25.4217371332
484.0 25.509519319
485.0 25.5974225002
486.0 25.6854465937
487.0 25.7735915165
488.0 25.8618571857
489.0 25.9502435189
490.0 26.0387504338
491.0 26.1273778483
492.0 26.2161256805
493.0 26.3049938488
494.0 26.3939822717
495.0 26.4830908681
496.0 26.572319557
497.0 26.6616682576
498.0 26.7511368894
499.0 26.840725372
500.0 26.9304336254
501.0 27.0202615696
502.0 27.1102091249
503.0 27.200276212
504.0 27.2904627514
505.0 27.3807686642
506.0 27.4711938714
507.0 27.5617382946
508.0 27.6524018552
509.0 27.7431844749
510.0 27.8340860759
511.0 27.9251065803
512.0 28.0162459104
513.0 28.1075039888
514.0 

878.0 68.8310189841
879.0 68.9617273126
880.0 69.0925348127
881.0 69.2234414471
882.0 69.354447178
883.0 69.4855519681
884.0 69.61675578
885.0 69.7480585763
886.0 69.8794603197
887.0 70.0109609729
888.0 70.1425604988
889.0 70.2742588603
890.0 70.4060560203
891.0 70.5379519417
892.0 70.6699465876
893.0 70.8020399211
894.0 70.9342319054
895.0 71.0665225036
896.0 71.198911679
897.0 71.331399395
898.0 71.4639856148
899.0 71.5966703019
900.0 71.7294534198
901.0 71.8623349321
902.0 71.9953148022
903.0 72.1283929939
904.0 72.2615694708
905.0 72.3948441967
906.0 72.5282171353
907.0 72.6616882506
908.0 72.7952575064
909.0 72.9289248667
910.0 73.0626902956
911.0 73.1965537569
912.0 73.330515215
913.0 73.464574634
914.0 73.598731978
915.0 73.7329872113
916.0 73.8673402984
917.0 74.0017912035
918.0 74.136339891
919.0 74.2709863256
920.0 74.4057304716
921.0 74.5405722938
922.0 74.6755117566
923.0 74.8105488249
924.0 74.9456834633
925.0 75.0809156366
926.0 75.2162453097
927.0 75.3516724475
928.0 75.

178.0 4.45203252007
179.0 4.49379623229
180.0 4.53571577962
181.0 4.57779087294
182.0 4.62002122525
183.0 4.66240655168
184.0 4.70494656943
185.0 4.74764099774
186.0 4.79048955789
187.0 4.83349197318
188.0 4.87664796884
189.0 4.91995727209
190.0 4.96341961206
191.0 5.0070347198
192.0 5.05080232823
193.0 5.09472217212
194.0 5.1387939881
195.0 5.18301751458
196.0 5.22739249179
197.0 5.27191866172
198.0 5.31659576811
199.0 5.36142355643
200.0 5.40640177384
201.0 5.45153016923
202.0 5.49680849311
203.0 5.54223649767
204.0 5.58781393673
205.0 5.6335405657
206.0 5.67941614162
207.0 5.72544042306
208.0 5.77161317019
209.0 5.81793414469
210.0 5.86440310977
211.0 5.91101983016
212.0 5.95778407205
213.0 6.00469560315
214.0 6.05175419257
215.0 6.09895961091
216.0 6.14631163016
217.0 6.19381002373
218.0 6.24145456644
219.0 6.28924503447
220.0 6.33718120537
221.0 6.38526285805
222.0 6.43348977273
223.0 6.48186173099
224.0 6.53037851568
225.0 6.57903991098
226.0 6.62784570232
227.0 6.67679567641
228

595.0 33.2700357113
596.0 33.3632812881
597.0 33.4566312248
598.0 33.5500854631
599.0 33.6436439449
600.0 33.7373066121
601.0 33.8310734068
602.0 33.9249442712
603.0 34.0189191477
604.0 34.1129979787
605.0 34.2071807068
606.0 34.3014672748
607.0 34.3958576255
608.0 34.4903517018
609.0 34.584949447
610.0 34.6796508042
611.0 34.7744557167
612.0 34.869364128
613.0 34.9643759818
614.0 35.0594912218
615.0 35.1547097917
616.0 35.2500316356
617.0 35.3454566975
618.0 35.4409849217
619.0 35.5366162524
620.0 35.6323506342
621.0 35.7281880116
622.0 35.8241283292
623.0 35.9201715319
624.0 36.0163175647
625.0 36.1125663724
626.0 36.2089179004
627.0 36.3053720938
628.0 36.4019288981
629.0 36.4985882588
630.0 36.5953501215
631.0 36.6922144318
632.0 36.7891811358
633.0 36.8862501793
634.0 36.9834215085
635.0 37.0806950695
636.0 37.1780708086
637.0 37.2755486722
638.0 37.3731286069
639.0 37.4708105594
640.0 37.5685944763
641.0 37.6664803046
642.0 37.7644679912
643.0 37.8625574832
644.0 37.9607487278
64

1017.0 81.2942656546
1018.0 81.4275349235
1019.0 81.5608914962
1020.0 81.6943353441
1021.0 81.8278664388
1022.0 81.9614847517
1023.0 82.0951902543
1024.0 82.2289829183
1025.0 82.3628627153
1026.0 82.4968296169
1027.0 82.6308835948
1028.0 82.7650246208
1029.0 82.8992526665
1030.0 83.0335677039
1031.0 83.1679697047
1032.0 83.3024586409
1033.0 83.4370344843
1034.0 83.5716972069
1035.0 83.7064467806
1036.0 83.8412831775
1037.0 83.9762063697
1038.0 84.1112163291
1039.0 84.2463130281
1040.0 84.3814964387
1041.0 84.5167665331
1042.0 84.6521232835
1043.0 84.7875666623
1044.0 84.9230966417
1045.0 85.0587131941
1046.0 85.1944162918
1047.0 85.3302059073
1048.0 85.466082013
1049.0 85.6020445814
1050.0 85.738093585
1051.0 85.8742289963
1052.0 86.010450788
1053.0 86.1467589327
1054.0 86.2831534029
1055.0 86.4196341715
1056.0 86.5562012111
1057.0 86.6928544945
1058.0 86.8295939945
1059.0 86.966419684
1060.0 87.1033315357
1061.0 87.2403295225
1062.0 87.3774136175
1063.0 87.5145837935
1064.0 87.6518400

258.0 7.56072083319
259.0 7.60962577508
260.0 7.65865676078
261.0 7.70781362847
262.0 7.7570962172
263.0 7.80650436679
264.0 7.85603791792
265.0 7.90569671203
266.0 7.95548059141
267.0 8.00538939909
268.0 8.05542297892
269.0 8.10558117552
270.0 8.15586383427
271.0 8.20627080133
272.0 8.25680192361
273.0 8.30745704876
274.0 8.3582360252
275.0 8.40913870207
276.0 8.46016492924
277.0 8.51131455733
278.0 8.56258743765
279.0 8.61398342225
280.0 8.66550236386
281.0 8.71714411594
282.0 8.76890853263
283.0 8.82079546876
284.0 8.87280477986
285.0 8.92493632211
286.0 8.9771899524
287.0 9.02956552826
288.0 9.0820629079
289.0 9.13468195017
290.0 9.18742251458
291.0 9.2402844613
292.0 9.29326765112
293.0 9.34637194548
294.0 9.39959720645
295.0 9.45294329671
296.0 9.50641007959
297.0 9.55999741902
298.0 9.61370517954
299.0 9.66753322629
300.0 9.72148142504
301.0 9.77554964212
302.0 9.82973774448
303.0 9.88404559966
304.0 9.93847307575
305.0 9.99302004146
306.0 10.0476863661
307.0 10.1024719194
308.0

676.0 37.6508558535
677.0 37.7437291728
678.0 37.836693993
679.0 37.9297502689
680.0 38.0228979558
681.0 38.1161370087
682.0 38.2094673829
683.0 38.3028890338
684.0 38.3964019168
685.0 38.4900059874
686.0 38.5837012012
687.0 38.6774875139
688.0 38.7713648814
689.0 38.8653332593
690.0 38.9593926038
691.0 39.0535428708
692.0 39.1477840164
693.0 39.2421159969
694.0 39.3365387686
695.0 39.4310522877
696.0 39.5256565108
697.0 39.6203513945
698.0 39.7151368952
699.0 39.8100129698
700.0 39.904979575
701.0 40.0000366677
702.0 40.0951842048
703.0 40.1904221435
704.0 40.2857504407
705.0 40.3811690536
706.0 40.4766779397
707.0 40.5722770561
708.0 40.6679663605
709.0 40.7637458102
710.0 40.8596153629
711.0 40.9555749762
712.0 41.0516246079
713.0 41.1477642159
714.0 41.2439937581
715.0 41.3403131924
716.0 41.436722477
717.0 41.5332215699
718.0 41.6298104294
719.0 41.7264890139
720.0 41.8232572817
721.0 41.9201151912
722.0 42.017062701
723.0 42.1140997697
724.0 42.2112263561
725.0 42.3084424188
726.

1091.0 83.606160046
1092.0 83.7339200546
1093.0 83.8617580847
1094.0 83.9896741122
1095.0 84.1176681136
1096.0 84.2457400651
1097.0 84.3738899429
1098.0 84.5021177234
1099.0 84.6304233829
1100.0 84.7588068978
1101.0 84.8872682444
1102.0 85.0158073993
1103.0 85.1444243388
1104.0 85.2731190395
1105.0 85.4018914778
1106.0 85.5307416304
1107.0 85.6596694737
1108.0 85.7886749845
1109.0 85.9177581392
1110.0 86.0469189146
1111.0 86.1761572873
1112.0 86.3054732341
1113.0 86.4348667317
1114.0 86.5643377569
1115.0 86.6938862864
1116.0 86.8235122971
1117.0 86.9532157658
1118.0 87.0829966695
1119.0 87.2128549849
1120.0 87.3427906892
1121.0 87.4728037591
1122.0 87.6028941717
1123.0 87.733061904
1124.0 87.8633069331
1125.0 87.9936292361
1126.0 88.1240287899
1127.0 88.2545055718
1128.0 88.3850595589
1129.0 88.5156907284
1130.0 88.6463990575
1131.0 88.7771845233
1132.0 88.9080471033
1133.0 89.0389867746
1134.0 89.1700035146
1135.0 89.3010973006
1136.0 89.43226811
1137.0 89.5635159202
1138.0 89.6948407

270.0 7.35933840097
271.0 7.40482247671
272.0 7.4504185823
273.0 7.49612658029
274.0 7.54194633389
275.0 7.58787770698
276.0 7.63392056408
277.0 7.68007477041
278.0 7.7263401918
279.0 7.77271669474
280.0 7.81920414636
281.0 7.86580241441
282.0 7.91251136729
283.0 7.95933087401
284.0 8.0062608042
285.0 8.05330102809
286.0 8.10045141655
287.0 8.14771184102
288.0 8.19508217355
289.0 8.24256228678
290.0 8.29015205396
291.0 8.33785134889
292.0 8.38566004596
293.0 8.43357802016
294.0 8.48160514701
295.0 8.52974130261
296.0 8.57798636364
297.0 8.62634020732
298.0 8.6748027114
299.0 8.72337375422
300.0 8.77205321464
301.0 8.82084097205
302.0 8.8697369064
303.0 8.91874089815
304.0 8.9678528283
305.0 9.01707257835
306.0 9.06640003035
307.0 9.11583506685
308.0 9.1653775709
309.0 9.21502742608
310.0 9.26478451644
311.0 9.31464872657
312.0 9.36461994152
313.0 9.41469804685
314.0 9.46488292861
315.0 9.51517447332
316.0 9.56557256799
317.0 9.61607710011
318.0 9.66668795764
319.0 9.71740502901
320.0 9

687.0 34.9001313531
688.0 34.9848403832
689.0 35.0696315355
690.0 35.1545047703
691.0 35.2394600478
692.0 35.3244973285
693.0 35.4096165728
694.0 35.4948177414
695.0 35.5801007948
696.0 35.6654656937
697.0 35.750912399
698.0 35.8364408715
699.0 35.9220510721
700.0 36.0077429619
701.0 36.0935165018
702.0 36.1793716532
703.0 36.2653083771
704.0 36.3513266349
705.0 36.4374263881
706.0 36.5236075979
707.0 36.6098702261
708.0 36.696214234
709.0 36.7826395835
710.0 36.8691462362
711.0 36.9557341541
712.0 37.0424032988
713.0 37.1291536325
714.0 37.2159851171
715.0 37.3028977147
716.0 37.3898913875
717.0 37.4769660978
718.0 37.5641218078
719.0 37.6513584799
720.0 37.7386760766
721.0 37.8260745604
722.0 37.9135538938
723.0 38.0011140396
724.0 38.0887549604
725.0 38.1764766191
726.0 38.2642789785
727.0 38.3521620015
728.0 38.4401256512
729.0 38.5281698906
730.0 38.6162946828
731.0 38.704499991
732.0 38.7927857786
733.0 38.8811520088
734.0 38.969598645
735.0 39.0581256508
736.0 39.1467329895
737.

1100.0 76.4810147764
1101.0 76.5969302135
1102.0 76.7129158598
1103.0 76.8289716942
1104.0 76.9450976953
1105.0 77.061293842
1106.0 77.1775601131
1107.0 77.2938964875
1108.0 77.4103029441
1109.0 77.5267794617
1110.0 77.6433260193
1111.0 77.7599425959
1112.0 77.8766291704
1113.0 77.9933857219
1114.0 78.1102122294
1115.0 78.2271086719
1116.0 78.3440750286
1117.0 78.4611112785
1118.0 78.5782174009
1119.0 78.6953933747
1120.0 78.8126391794
1121.0 78.9299547939
1122.0 79.0473401977
1123.0 79.1647953699
1124.0 79.2823202899
1125.0 79.3999149368
1126.0 79.5175792902
1127.0 79.6353133293
1128.0 79.7531170335
1129.0 79.8709903822
1130.0 79.9889333549
1131.0 80.106945931
1132.0 80.22502809
1133.0 80.3431798113
1134.0 80.4614010747
1135.0 80.5796918594
1136.0 80.6980521453
1137.0 80.8164819117
1138.0 80.9349811385
1139.0 81.0535498052
1140.0 81.1721878915
1141.0 81.2908953771
1142.0 81.4096722417
1143.0 81.528518465
1144.0 81.6474340269
1145.0 81.7664189071
1146.0 81.8854730854
1147.0 82.00459654

200.0 3.95210367166
201.0 3.9850927288
202.0 4.01819138435
203.0 4.05139945714
204.0 4.08471676721
205.0 4.11814313577
206.0 4.1516783852
207.0 4.18532233903
208.0 4.21907482193
209.0 4.2529356597
210.0 4.28690467925
211.0 4.32098170858
212.0 4.35516657678
213.0 4.38945911404
214.0 4.4238591516
215.0 4.45836652174
216.0 4.49298105779
217.0 4.52770259413
218.0 4.56253096613
219.0 4.59746601019
220.0 4.63250756369
221.0 4.66765546502
222.0 4.70290955352
223.0 4.73826966951
224.0 4.77373565428
225.0 4.80930735003
226.0 4.84498459993
227.0 4.88076724806
228.0 4.91665513943
229.0 4.95264811994
230.0 4.9887460364
231.0 5.02494873651
232.0 5.06125606885
233.0 5.09766788287
234.0 5.13418402887
235.0 5.17080435802
236.0 5.20752872235
237.0 5.24435697468
238.0 5.28128896871
239.0 5.31832455893
240.0 5.35546360066
241.0 5.39270595
242.0 5.43005146388
243.0 5.4675
244.0 5.50505141684
245.0 5.54270557366
246.0 5.5804623305
247.0 5.61832154812
248.0 5.65628308809
249.0 5.69434681267
250.0 5.73251258

619.0 25.9774240695
620.0 26.0474063272
621.0 26.117463875
622.0 26.1875966727
623.0 26.2578046798
624.0 26.328087856
625.0 26.3984461613
626.0 26.4688795556
627.0 26.5393879987
628.0 26.6099714508
629.0 26.6806298721
630.0 26.7513632228
631.0 26.8221714633
632.0 26.8930545539
633.0 26.9640124551
634.0 27.0350451277
635.0 27.1061525321
636.0 27.1773346292
637.0 27.2485913798
638.0 27.3199227448
639.0 27.3913286852
640.0 27.4628091621
641.0 27.5343641367
642.0 27.6059935701
643.0 27.6776974237
644.0 27.749475659
645.0 27.8213282373
646.0 27.8932551203
647.0 27.9652562695
648.0 28.0373316468
649.0 28.1094812138
650.0 28.1817049326
651.0 28.2540027649
652.0 28.3263746729
653.0 28.3988206187
654.0 28.4713405645
655.0 28.5439344724
656.0 28.616602305
657.0 28.6893440245
658.0 28.7621595935
659.0 28.8350489745
660.0 28.9080121302
661.0 28.9810490234
662.0 29.0541596167
663.0 29.1273438731
664.0 29.2006017555
665.0 29.273933227
666.0 29.3473382507
667.0 29.4208167896
668.0 29.4943688071
669.0

1032.0 60.8944666757
1033.0 60.992842214
1034.0 61.0912812613
1035.0 61.1897837973
1036.0 61.2883498014
1037.0 61.3869792532
1038.0 61.4856721323
1039.0 61.5844284183
1040.0 61.6832480909
1041.0 61.7821311298
1042.0 61.8810775146
1043.0 61.9800872251
1044.0 62.0791602411
1045.0 62.1782965423
1046.0 62.2774961085
1047.0 62.3767589196
1048.0 62.4760849554
1049.0 62.5754741958
1050.0 62.6749266207
1051.0 62.7744422101
1052.0 62.8740209439
1053.0 62.9736628022
1054.0 63.0733677648
1055.0 63.1731358118
1056.0 63.2729669234
1057.0 63.3728610796
1058.0 63.4728182605
1059.0 63.5728384462
1060.0 63.6729216169
1061.0 63.7730677528
1062.0 63.8732768342
1063.0 63.9735488412
1064.0 64.073883754
1065.0 64.1742815531
1066.0 64.2747422187
1067.0 64.3752657311
1068.0 64.4758520707
1069.0 64.5765012179
1070.0 64.6772131531
1071.0 64.7779878568
1072.0 64.8788253093
1073.0 64.9797254911
1074.0 65.0806883829
1075.0 65.1817139651
1076.0 65.2828022182
1077.0 65.3839531228
1078.0 65.4851666596
1079.0 65.58644

23.0 0.0926228315852
24.0 0.0994314401905
25.0 0.10643186561
26.0 0.113621514453
27.0 0.120997928157
28.0 0.128558771183
29.0 0.136301820623
30.0 0.144224957031
31.0 0.15232615627
32.0 0.160603482262
33.0 0.16905508049
34.0 0.17767917217
35.0 0.186474048995
36.0 0.195438068395
37.0 0.204569649227
38.0 0.213867267868
39.0 0.223329454649
40.0 0.232954790596
41.0 0.242741904449
42.0 0.25268946992
43.0 0.262796203177
44.0 0.273060860517
45.0 0.283482236226
46.0 0.294059160589
47.0 0.304790498052
48.0 0.315675145514
49.0 0.326712030737
50.0 0.337900110865
51.0 0.349238371045
52.0 0.360725823137
53.0 0.372361504503
54.0 0.384144476885
55.0 0.396073825336
56.0 0.40814865723
57.0 0.420368101326
58.0 0.432731306885
59.0 0.445237442842
60.0 0.457885697021
61.0 0.470675275401
62.0 0.483605401411
63.0 0.496675315276
64.0 0.509884273386
65.0 0.523231547709
66.0 0.536716425222
67.0 0.550338207386
68.0 0.56409620963
69.0 0.577989760877
70.0 0.592018203079
71.0 0.606180890787
72.0 0.620477190729
73.0 

436.0 12.4829091329
437.0 12.5306631475
438.0 12.5784900689
439.0 12.6263898418
440.0 12.6743624107
441.0 12.7224077205
442.0 12.7705257161
443.0 12.8187163426
444.0 12.8669795455
445.0 12.91531527
446.0 12.963723462
447.0 13.0122040671
448.0 13.0607570314
449.0 13.1093823009
450.0 13.158079822
451.0 13.206849541
452.0 13.2556914046
453.0 13.3046053596
454.0 13.3535913528
455.0 13.4026493314
456.0 13.4517792424
457.0 13.5009810335
458.0 13.5502546519
459.0 13.5996000455
460.0 13.6490171621
461.0 13.6985059497
462.0 13.7480663564
463.0 13.7976983304
464.0 13.8474018203
465.0 13.8971767747
466.0 13.9470231422
467.0 13.9969408717
468.0 14.0469299123
469.0 14.0969902131
470.0 14.1471217235
471.0 14.1973243929
472.0 14.2475981709
473.0 14.2979430073
474.0 14.348358852
475.0 14.3988456549
476.0 14.4494033663
477.0 14.5000319365
478.0 14.5507313158
479.0 14.601501455
480.0 14.6523423047
481.0 14.7032538158
482.0 14.7542359392
483.0 14.8052886262
484.0 14.8564118279
485.0 14.9076054959
486.0 1

859.0 38.650958354
860.0 38.7259796091
861.0 38.8010590427
862.0 38.8761966323
863.0 38.9513923555
864.0 39.0266461898
865.0 39.1019581127
866.0 39.1773281018
867.0 39.2527561349
868.0 39.3282421895
869.0 39.4037862434
870.0 39.4793882743
871.0 39.55504826
872.0 39.6307661783
873.0 39.7065420071
874.0 39.7823757243
875.0 39.8582673076
876.0 39.9342167352
877.0 40.010223985
878.0 40.086289035
879.0 40.1624118632
880.0 40.2385924477
881.0 40.3148307667
882.0 40.3911267982
883.0 40.4674805205
884.0 40.5438919118
885.0 40.6203609504
886.0 40.6968876144
887.0 40.7734718822
888.0 40.8501137323
889.0 40.9268131428
890.0 41.0035700923
891.0 41.0803845592
892.0 41.1572565219
893.0 41.2341859591
894.0 41.3111728491
895.0 41.3882171706
896.0 41.4653189022
897.0 41.5424780225
898.0 41.6196945102
899.0 41.6969683439
900.0 41.7742995025
901.0 41.8516879647
902.0 41.9291337092
903.0 42.0066367148
904.0 42.0841969606
905.0 42.1618144252
906.0 42.2394890877
907.0 42.317220927
908.0 42.395009922
909.0 4

1263.0 73.481369976
1264.0 73.5783622716
1265.0 73.675405737
1266.0 73.7725003587
1267.0 73.8696461231
1268.0 73.966843017
1269.0 74.0640910267
1270.0 74.1613901389
1271.0 74.2587403402
1272.0 74.3561416171
1273.0 74.4535939563
1274.0 74.5510973444
1275.0 74.648651768
1276.0 74.7462572139
1277.0 74.8439136685
1278.0 74.9416211188
1279.0 75.0393795512
1280.0 75.1371889526
1281.0 75.2350493097
1282.0 75.3329606092
1283.0 75.4309228378
1284.0 75.5289359824
1285.0 75.6270000296
1286.0 75.7251149664
1287.0 75.8232807794
1288.0 75.9214974556
1289.0 76.0197649817
1290.0 76.1180833446
1291.0 76.2164525312
1292.0 76.3148725283
1293.0 76.4133433228
1294.0 76.5118649016
1295.0 76.6104372517
1296.0 76.70906036
1297.0 76.8077342133
1298.0 76.9064587987
1299.0 77.0052341032
1300.0 77.1040601136
1301.0 77.2029368171
1302.0 77.3018642006
1303.0 77.4008422511
1304.0 77.4998709556
1305.0 77.5989503013
1306.0 77.6980802752
1307.0 77.7972608643
1308.0 77.8964920558
1309.0 77.9957738367
1310.0 78.095106194

128.0 1.33627482152
129.0 1.353719505
130.0 1.37125457584
131.0 1.38887980168
132.0 1.40659495253
133.0 1.42439980073
134.0 1.44229412091
135.0 1.46027768994
136.0 1.47835028689
137.0 1.49651169304
138.0 1.51476169176
139.0 1.53310006854
140.0 1.55152661094
141.0 1.57004110852
142.0 1.58864335286
143.0 1.60733313751
144.0 1.62611025791
145.0 1.64497451143
146.0 1.6639256973
147.0 1.68296361659
148.0 1.70208807218
149.0 1.72129886871
150.0 1.7405958126
151.0 1.75997871199
152.0 1.77944737669
153.0 1.79900161822
154.0 1.81864124972
155.0 1.83836608596
156.0 1.85817594331
157.0 1.8780706397
158.0 1.89804999464
159.0 1.91811382913
160.0 1.93826196569
161.0 1.95849422832
162.0 1.9788104425
163.0 1.99921043511
164.0 2.01969403449
165.0 2.04026107034
166.0 2.06091137377
167.0 2.08164477724
168.0 2.10246111455
169.0 2.12336022081
170.0 2.14434193244
171.0 2.16540608717
172.0 2.18655252395
173.0 2.20778108303
174.0 2.22909160586
175.0 2.25048393512
176.0 2.27195791468
177.0 2.29351338963
178.0 

546.0 14.9922531606
547.0 15.0380449923
548.0 15.0838926678
549.0 15.129796153
550.0 15.175755414
551.0 15.2217704169
552.0 15.2678411282
553.0 15.313967514
554.0 15.3601495408
555.0 15.4063871752
556.0 15.4526803836
557.0 15.4990291328
558.0 15.5454333895
559.0 15.5918931205
560.0 15.6384082927
561.0 15.6849788731
562.0 15.7316048288
563.0 15.7782861269
564.0 15.8250227346
565.0 15.8718146192
566.0 15.918661748
567.0 15.9655640886
568.0 16.0125216084
569.0 16.059534275
570.0 16.1066020562
571.0 16.1537249196
572.0 16.2009028331
573.0 16.2481357646
574.0 16.295423682
575.0 16.3427665535
576.0 16.3901643471
577.0 16.437617031
578.0 16.4851245736
579.0 16.5326869431
580.0 16.5803041079
581.0 16.6279760366
582.0 16.6757026978
583.0 16.72348406
584.0 16.7713200919
585.0 16.8192107624
586.0 16.8671560403
587.0 16.9151558945
588.0 16.963210294
589.0 17.0113192079
590.0 17.0594826052
591.0 17.1077004553
592.0 17.1559727273
593.0 17.2042993906
594.0 17.2526804146
595.0 17.3011157689
596.0 17.3

966.0 38.8008327558
967.0 38.8678000092
968.0 38.9348134469
969.0 39.001873053
970.0 39.0689788116
971.0 39.1361307068
972.0 39.2033287229
973.0 39.2705728439
974.0 39.3378630542
975.0 39.4051993378
976.0 39.4725816792
977.0 39.5400100624
978.0 39.6074844718
979.0 39.6750048918
980.0 39.7425713065
981.0 39.8101837005
982.0 39.877842058
983.0 39.9455463635
984.0 40.0132966014
985.0 40.081092756
986.0 40.148934812
987.0 40.2168227536
988.0 40.2847565655
989.0 40.3527362322
990.0 40.4207617381
991.0 40.4888330679
992.0 40.5569502061
993.0 40.6251131374
994.0 40.6933218463
995.0 40.7615763175
996.0 40.8298765357
997.0 40.8982224856
998.0 40.9666141518
999.0 41.0350515191
1000.0 41.1035345722
1001.0 41.1720632959
1002.0 41.240637675
1003.0 41.3092576943
1004.0 41.3779233386
1005.0 41.4466345927
1006.0 41.5153914416
1007.0 41.5841938701
1008.0 41.6530418632
1009.0 41.7219354057
1010.0 41.7908744826
1011.0 41.8598590788
1012.0 41.9288891794
1013.0 41.9979647694
1014.0 42.0670858338
1015.0 42.

1367.0 69.2085940715
1368.0 69.2929947893
1369.0 69.3774366481
1370.0 69.4619196378
1371.0 69.5464437485
1372.0 69.6310089701
1373.0 69.7156152927
1374.0 69.8002627062
1375.0 69.8849512008
1376.0 69.9696807664
1377.0 70.0544513932
1378.0 70.139263071
1379.0 70.2241157901
1380.0 70.3090095405
1381.0 70.3939443123
1382.0 70.4789200955
1383.0 70.5639368804
1384.0 70.6489946569
1385.0 70.7340934153
1386.0 70.8192331456
1387.0 70.904413838
1388.0 70.9896354827
1389.0 71.0748980698
1390.0 71.1602015895
1391.0 71.245546032
1392.0 71.3309313874
1393.0 71.416357646
1394.0 71.501824798
1395.0 71.5873328336
1396.0 71.672881743
1397.0 71.7584715164
1398.0 71.8441021442
1399.0 71.9297736165
1400.0 72.0154859237
1401.0 72.101239056
1402.0 72.1870330036
1403.0 72.272867757
1404.0 72.3587433063
1405.0 72.4446596419
1406.0 72.5306167542
1407.0 72.6166146334
1408.0 72.7026532699
1409.0 72.788732654
1410.0 72.8748527761
1411.0 72.9610136266
1412.0 73.0472151959
1413.0 73.1334574742
1414.0 73.2197404521
1

42.0 0.15918439112
43.0 0.165551234108
44.0 0.172017563034
45.0 0.178582618346
46.0 0.18524566317
47.0 0.192005982152
48.0 0.198862880381
49.0 0.20581568239
50.0 0.21286373122
51.0 0.220006387556
52.0 0.227243028905
53.0 0.234573048847
54.0 0.241995856314
55.0 0.249510874926
56.0 0.257117542365
57.0 0.264815309783
58.0 0.272603641247
59.0 0.280482013219
60.0 0.288449914061
61.0 0.296506843571
62.0 0.30465231254
63.0 0.312885842339
64.0 0.321206964525
65.0 0.329615220464
66.0 0.338110160981
67.0 0.346691346023
68.0 0.355358344339
69.0 0.364110733176
70.0 0.37294809799
71.0 0.381870032173
72.0 0.39087613679
73.0 0.399966020326
74.0 0.409139298454
75.0 0.418395593801
76.0 0.427734535736
77.0 0.437155760158
78.0 0.446658909298
79.0 0.456243631532
80.0 0.465909581193
81.0 0.475656418402
82.0 0.485483808898
83.0 0.495391423878
84.0 0.505378939841
85.0 0.515446038443
86.0 0.525592406354
87.0 0.53581773512
88.0 0.546121721035
89.0 0.556504065009
90.0 0.566964472453
91.0 0.577502653156
92.0 0.5

457.0 8.50508509914
458.0 8.53612553369
459.0 8.56721118376
460.0 8.59834201647
461.0 8.62951799906
462.0 8.66073909886
463.0 8.6920052833
464.0 8.72331651989
465.0 8.75467277625
466.0 8.78607402009
467.0 8.81752021918
468.0 8.84901134144
469.0 8.88054735483
470.0 8.91212822744
471.0 8.94375392741
472.0 8.97542442301
473.0 9.00713968257
474.0 9.03889967453
475.0 9.07070436741
476.0 9.10255372982
477.0 9.13444773045
478.0 9.16638633809
479.0 9.19836952161
480.0 9.23039724997
481.0 9.26246949221
482.0 9.29458621746
483.0 9.32674739494
484.0 9.35895299396
485.0 9.39120298389
486.0 9.4234973342
487.0 9.45583601445
488.0 9.48821899428
489.0 9.5206462434
490.0 9.55311773163
491.0 9.58563342883
492.0 9.61819330499
493.0 9.65079733014
494.0 9.68344547442
495.0 9.71613770804
496.0 9.74887400129
497.0 9.78165432453
498.0 9.81447864822
499.0 9.84734694289
500.0 9.88025917914
501.0 9.91321532766
502.0 9.94621535921
503.0 9.97925924464
504.0 10.0123469549
505.0 10.0454784609
506.0 10.0786537338
507

875.0 25.1091349966
876.0 25.1569801379
877.0 25.2048617048
878.0 25.2527796837
879.0 25.3007340605
880.0 25.3487248215
881.0 25.3967519529
882.0 25.444815441
883.0 25.492915272
884.0 25.5410514322
885.0 25.5892239078
886.0 25.6374326853
887.0 25.6856777509
888.0 25.7339590909
889.0 25.7822766919
890.0 25.8306305401
891.0 25.8790206219
892.0 25.927446924
893.0 25.9759094325
894.0 26.0244081342
895.0 26.0729430154
896.0 26.1215140627
897.0 26.1701212627
898.0 26.2187646018
899.0 26.2674440667
900.0 26.3161596439
901.0 26.3649113202
902.0 26.413699082
903.0 26.4625229162
904.0 26.5113828093
905.0 26.560278748
906.0 26.6092107192
907.0 26.6581787095
908.0 26.7071827056
909.0 26.7562226945
910.0 26.8052986627
911.0 26.8544105973
912.0 26.9035584849
913.0 26.9527423125
914.0 27.0019620669
915.0 27.0512177351
916.0 27.1005093038
917.0 27.1498367602
918.0 27.1992000911
919.0 27.2485992834
920.0 27.2980343242
921.0 27.3475052006
922.0 27.3970118994
923.0 27.4465544077
924.0 27.4961327127
925.0

1281.0 47.3951111576
1282.0 47.4567914112
1283.0 47.5185037482
1284.0 47.5802481602
1285.0 47.6420246389
1286.0 47.7038331759
1287.0 47.765673763
1288.0 47.8275463919
1289.0 47.8894510542
1290.0 47.9513877418
1291.0 48.0133564462
1292.0 48.0753571592
1293.0 48.1373898726
1294.0 48.1994545781
1295.0 48.2615512676
1296.0 48.3236799326
1297.0 48.385840565
1298.0 48.4480331567
1299.0 48.5102576993
1300.0 48.5725141848
1301.0 48.6348026048
1302.0 48.6971229512
1303.0 48.7594752159
1304.0 48.8218593906
1305.0 48.8842754672
1306.0 48.9467234376
1307.0 49.0092032936
1308.0 49.0717150271
1309.0 49.1342586299
1310.0 49.1968340939
1311.0 49.2594414111
1312.0 49.3220805733
1313.0 49.3847515725
1314.0 49.4474544005
1315.0 49.5101890493
1316.0 49.5729555107
1317.0 49.6357537768
1318.0 49.6985838395
1319.0 49.7614456908
1320.0 49.8243393226
1321.0 49.8872647268
1322.0 49.9502218955
1323.0 50.0132108207
1324.0 50.0762314943
1325.0 50.1392839084
1326.0 50.202368055
1327.0 50.265483926
1328.0 50.3286315

1680.0 74.4732773249
1681.0 74.5471742027
1682.0 74.621100393
1683.0 74.69505589
1684.0 74.7690406879
1685.0 74.8430547809
1686.0 74.9170981633
1687.0 74.9911708291
1688.0 75.0652727727
1689.0 75.1394039883
1690.0 75.21356447
1691.0 75.2877542122
1692.0 75.3619732089
1693.0 75.4362214545
1694.0 75.5104989433
1695.0 75.5848056694
1696.0 75.659141627
1697.0 75.7335068106
1698.0 75.8079012142
1699.0 75.8823248322
1700.0 75.9567776589
1701.0 76.0312596885
1702.0 76.1057709153
1703.0 76.1803113335
1704.0 76.2548809375
1705.0 76.3294797215
1706.0 76.4041076799
1707.0 76.4787648069
1708.0 76.5534510969
1709.0 76.6281665441
1710.0 76.7029111429
1711.0 76.7776848875
1712.0 76.8524877724
1713.0 76.9273197917
1714.0 77.0021809399
1715.0 77.0770712113
1716.0 77.1519906003
1717.0 77.2269391011
1718.0 77.3019167081
1719.0 77.3769234157
1720.0 77.4519592182
1721.0 77.5270241099
1722.0 77.6021180854
1723.0 77.6772411388
1724.0 77.7523932646
1725.0 77.8275744573
1726.0 77.902784711
1727.0 77.9780240203

55.0 0.157182001749
56.0 0.161973901962
57.0 0.166823191565
58.0 0.171729532942
59.0 0.176692596286
60.0 0.181712059283
61.0 0.186787606827
62.0 0.191918930734
63.0 0.197105729489
64.0 0.202347707989
65.0 0.207644577314
66.0 0.212996054502
67.0 0.218401862336
68.0 0.223861729145
69.0 0.229375388611
70.0 0.234942579588
71.0 0.24056304593
72.0 0.246236536321
73.0 0.251962804126
74.0 0.257741607231
75.0 0.263572707907
76.0 0.269455872671
77.0 0.275390872153
78.0 0.281377480974
79.0 0.287415477624
80.0 0.293504644346
81.0 0.299644767031
82.0 0.305835635107
83.0 0.31207704144
84.0 0.318368782239
85.0 0.32471065696
86.0 0.331102468215
87.0 0.337544021693
88.0 0.344035126068
89.0 0.350575592929
90.0 0.357165236693
91.0 0.363803874541
92.0 0.370491326341
93.0 0.377227414581
94.0 0.384011964304
95.0 0.390844803044
96.0 0.397725760762
97.0 0.404654669792
98.0 0.41163136478
99.0 0.418655682627
100.0 0.425727462441
101.0 0.432846545482
102.0 0.440012775111
103.0 0.447225996746
104.0 0.454486057811

465.0 5.51509825787
466.0 5.53487980192
467.0 5.55468966601
468.0 5.57452782992
469.0 5.59439427347
470.0 5.61428897655
471.0 5.63421191911
472.0 5.65416308114
473.0 5.67414244271
474.0 5.69414998392
475.0 5.71418568494
476.0 5.734249526
477.0 5.75434148738
478.0 5.77446154941
479.0 5.79460969249
480.0 5.81478589706
481.0 5.83499014362
482.0 5.85522241272
483.0 5.87548268497
484.0 5.89577094103
485.0 5.91608716162
486.0 5.93643132749
487.0 5.95680341948
488.0 5.97720341845
489.0 5.99763130533
490.0 6.0180870611
491.0 6.03857066678
492.0 6.05908210346
493.0 6.07962135226
494.0 6.10018839437
495.0 6.12078321102
496.0 6.1414057835
497.0 6.16205609314
498.0 6.18273412132
499.0 6.20343984948
500.0 6.22417325911
501.0 6.24493433173
502.0 6.26572304893
503.0 6.28653939234
504.0 6.30738334364
505.0 6.32825488456
506.0 6.34915399688
507.0 6.37008066242
508.0 6.39103486305
509.0 6.4120165807
510.0 6.43302579733
511.0 6.45406249495
512.0 6.47512665564
513.0 6.4962182615
514.0 6.51733729467
515.0 

879.0 15.9384637103
880.0 15.9686959953
881.0 15.9989511922
882.0 16.0292292924
883.0 16.0595302872
884.0 16.0898541679
885.0 16.120200926
886.0 16.1505705527
887.0 16.1809630396
888.0 16.2113783779
889.0 16.2418165591
890.0 16.2722775747
891.0 16.3027614161
892.0 16.3332680748
893.0 16.3637975421
894.0 16.3943498097
895.0 16.4249248689
896.0 16.4555227114
897.0 16.4861433286
898.0 16.516786712
899.0 16.5474528533
900.0 16.5781417439
901.0 16.6088533754
902.0 16.6395877395
903.0 16.6703448277
904.0 16.7011246316
905.0 16.7319271429
906.0 16.7627523531
907.0 16.793600254
908.0 16.8244708371
909.0 16.8553640942
910.0 16.8862800169
911.0 16.917218597
912.0 16.9481798261
913.0 16.9791636959
914.0 17.0101701983
915.0 17.0411993248
916.0 17.0722510674
917.0 17.1033254177
918.0 17.1344223675
919.0 17.1655419087
920.0 17.1966840329
921.0 17.2278487321
922.0 17.2590359981
923.0 17.2902458227
924.0 17.3214781977
925.0 17.3527331151
926.0 17.3840105666
927.0 17.4153105442
928.0 17.4466330398
929.

1282.0 29.8959052297
1283.0 29.9347815659
1284.0 29.9736781081
1285.0 30.0125948511
1286.0 30.0515317895
1287.0 30.0904889182
1288.0 30.129466232
1289.0 30.1684637256
1290.0 30.2074813938
1291.0 30.2465192313
1292.0 30.2855772331
1293.0 30.3246553938
1294.0 30.3637537082
1295.0 30.4028721713
1296.0 30.4420107777
1297.0 30.4811695224
1298.0 30.5203484001
1299.0 30.5595474056
1300.0 30.5987665338
1301.0 30.6380057796
1302.0 30.6772651378
1303.0 30.7165446031
1304.0 30.7558441706
1305.0 30.795163835
1306.0 30.8345035912
1307.0 30.8738634341
1308.0 30.9132433585
1309.0 30.9526433594
1310.0 30.9920634316
1311.0 31.03150357
1312.0 31.0709637695
1313.0 31.110444025
1314.0 31.1499443314
1315.0 31.1894646837
1316.0 31.2290050767
1317.0 31.2685655054
1318.0 31.3081459647
1319.0 31.3477464495
1320.0 31.3873669548
1321.0 31.4270074755
1322.0 31.4666680066
1323.0 31.5063485429
1324.0 31.5460490796
1325.0 31.5857696114
1326.0 31.6255101335
1327.0 31.6652706408
1328.0 31.7050511282
1329.0 31.74485159

1681.0 46.9617769941
1682.0 47.0083475757
1683.0 47.0549366194
1684.0 47.1015441216
1685.0 47.1481700785
1686.0 47.1948144865
1687.0 47.2414773419
1688.0 47.2881586412
1689.0 47.3348583807
1690.0 47.3815765567
1691.0 47.4283131656
1692.0 47.4750682038
1693.0 47.5218416676
1694.0 47.5686335533
1695.0 47.6154438575
1696.0 47.6622725764
1697.0 47.7091197065
1698.0 47.7559852441
1699.0 47.8028691856
1700.0 47.8497715273
1701.0 47.8966922658
1702.0 47.9436313973
1703.0 47.9905889183
1704.0 48.0375648252
1705.0 48.0845591143
1706.0 48.1315717822
1707.0 48.1786028251
1708.0 48.2256522395
1709.0 48.2727200219
1710.0 48.3198061686
1711.0 48.366910676
1712.0 48.4140335406
1713.0 48.4611747588
1714.0 48.508334327
1715.0 48.5555122417
1716.0 48.6027084993
1717.0 48.6499230962
1718.0 48.6971560289
1719.0 48.7444072937
1720.0 48.7916768873
1721.0 48.8389648059
1722.0 48.8862710461
1723.0 48.9335956043
1724.0 48.9809384769
1725.0 49.0282996605
1726.0 49.0756791514
1727.0 49.1230769462
1728.0 49.17049

2075.0 66.7055292966
2076.0 66.7591166416
2077.0 66.8127211979
2078.0 66.8663429626
2079.0 66.9199819332
2080.0 66.9736381067
2081.0 67.0273114805
2082.0 67.0810020518
2083.0 67.1347098178
2084.0 67.1884347758
2085.0 67.242176923
2086.0 67.2959362568
2087.0 67.3497127742
2088.0 67.4035064727
2089.0 67.4573173494
2090.0 67.5111454017
2091.0 67.5649906267
2092.0 67.6188530217
2093.0 67.672732584
2094.0 67.7266293109
2095.0 67.7805431997
2096.0 67.8344742475
2097.0 67.8884224517
2098.0 67.9423878095
2099.0 67.9963703183
2100.0 68.0503699753
2101.0 68.1043867777
2102.0 68.1584207228
2103.0 68.212471808
2104.0 68.2665400306
2105.0 68.3206253877
2106.0 68.3747278767
2107.0 68.4288474948
2108.0 68.4829842395
2109.0 68.5371381078
2110.0 68.5913090973
2111.0 68.645497205
2112.0 68.6997024285
2113.0 68.7539247648
2114.0 68.8081642114
2115.0 68.8624207655
2116.0 68.9166944245
2117.0 68.9709851856
2118.0 69.0252930461
2119.0 69.0796180034
2120.0 69.1339600548
2121.0 69.1883191976
2122.0 69.2426954

2476.0 89.546661717
2477.0 89.6069462595
2478.0 89.6672470295
2479.0 89.7275640245
2480.0 89.7878972426
2481.0 89.8482466814
2482.0 89.9086123388
2483.0 89.9689942127
2484.0 90.0293923008
2485.0 90.089806601
2486.0 90.1502371111
2487.0 90.2106838289
2488.0 90.2711467522
2489.0 90.331625879
2490.0 90.392121207
2491.0 90.452632734
2492.0 90.5131604579
2493.0 90.5737043765
2494.0 90.6342644876
2495.0 90.6948407891
2496.0 90.7554332788
2497.0 90.8160419546
2498.0 90.8766668143
2499.0 90.9373078557
2500.0 90.9979650767
2501.0 91.0586384751
2502.0 91.1193280488
2503.0 91.1800337955
2504.0 91.2407557132
2505.0 91.3014937997
2506.0 91.3622480529
2507.0 91.4230184706
2508.0 91.4838050506
2509.0 91.5446077907
2510.0 91.605426689
2511.0 91.6662617431
2512.0 91.727112951
2513.0 91.7879803106
2514.0 91.8488638196
2515.0 91.9097634759
2516.0 91.9706792774
2517.0 92.031611222
2518.0 92.0925593074
2519.0 92.1535235317
2520.0 92.2145038926
2521.0 92.275500388
2522.0 92.3365130157
2523.0 92.3975417738
2

In [2]:
import numpy as np
print(np.array(aa.QCompare))
pickle.dump(aa.QCompare, open('QCompare1.out', 'wb'))

[[ 0.70674542  1.04447308  1.07520897]
 [ 0.79508894  1.10027339  1.02124878]
 [ 0.90867267  1.17217705  0.96565203]
 [ 1.06011779  1.26795133  0.90844917]
 [ 1.27214125  1.40212423  0.84925041]
 [ 1.59017594  1.60330379  0.78779758]
 [ 2.12023456  1.93846584  0.72382345]
 [ 3.18035266  2.60890182  0.65705057]
 [ 6.36069983  4.6197239   0.58689523]]


In [3]:
f = open('QCompare2.out', 'rb')
b = pickle.load(f)
print(np.array(b))

[[ 0.84148728  1.06977173  1.01301966]
 [ 0.94667276  1.15720123  0.97927684]
 [ 1.08191221  1.26941486  0.94511979]
 [ 1.26223035  1.41911496  0.91021206]
 [ 1.5146767   1.62864311  0.87468433]
 [ 1.89334614  1.94297933  0.83853271]
 [ 2.52445813  2.46708036  0.80175284]
 [ 3.78668611  3.5140062   0.76381565]]


In [4]:
f = open('QCompare3.out', 'rb')
b = pickle.load(f)
print(np.array(b))

[[ 0.76545155  1.04293332  1.03604723]
 [ 0.82433253  1.09328183  1.01252682]
 [ 0.89302684  1.15144315  0.98850717]
 [ 0.97421033  1.21839553  0.96303234]
 [ 1.07163167  1.30053906  0.93821036]
 [ 1.1907024   1.40387805  0.91464651]
 [ 1.33953948  1.52600953  0.88745963]
 [ 1.53090292  1.68780001  0.86182613]
 [ 1.78605287  1.90876028  0.83774774]
 [ 2.14326324  2.21154285  0.81129801]
 [ 2.6790796   2.66571563  0.78448781]
 [ 3.57210048  3.42276247  0.75731715]
 [ 5.35815303  4.93716962  0.72978807]]
